[gravity]
host = "0.0.0.0:32803"

[subscriber]
subscriber_id = "kafka_exporter"
subscriber_name = "KAFKA Exporter"
state_store = "./statestore"
worker_count = 4
verbose = true

[rules]
subscription = "./settings/subscriptions.json"

[kafka]
host = "192.168.1.170:31090"
