[gravity]
domain = "gravity"
host = "0.0.0.0:32803"

[subscriber]
subscriberID = "kafka_exporter"
subscriberName = "Kafka Exporter"
stateStore = "./statestore"
workerCount = 4
chunkSize = 2048
verbose = true
pipelineStart = 0
pipelineEnd = -1

# Authentication
appID = "anonymous"
accessKey = ""

[initialLoad]
enabled = false
omittedCount = 100000

[rules]
subscription = "./settings/subscriptions.json"

[kafka]
hosts = "192.168.1.170:31090,192.168.1.171:31090"
